<div class=alinea>
    <input type="checkbox" id="sass" name="f&l[]" value="sass">
    <label for="sass">Sass</label>
    <br>

    <input type="checkbox" id="bootstrap" name="f&l[]" value="bootstrap">
    <label for="bootstrap">Bootstrap</label>
    <br>

    <input type="checkbox" id="symfony" name="f&l[]" value="symfony">
    <label for="symfony">Symfony</label>
    <br>

    <input type="checkbox" id="laravel" name="f&l[]" value="laravel">
    <label for="laravel">Laravel</label>
    <br>
</div>
