<div class=alinea>

    <label for="nom">Nom</label>
    <br>
    <input type="text" id="nom" name="nom" />
    <br>
    <br>
    
    <label for="prenom">Prénom</label>
    <br>
    <input type="text" id="prenom" name="prenom" />
    <br>
    <br>
    
    <label for="email">Email</label>
    <br>
    <input type="email" id="email" name="email" />
    <br>
    <br>

    <label for="telephone">Téléphone</label>
    <br>
    <input type="text" id="telephone" name="telephone" />
    <br>
    <br>

    <label for="linkedin">Linkedin</label>
    <br>
    <input type="text" id="linkedin" name="linkedin" />
    <br>
    <br>
    
    <label for="github">GitHub</label>
    <br>
    <input type="text" id="github" name="github" />
    <br>
    <br>
    
    <label for="biographie">Biographie</label>
    <br>
    <textarea id="biographie" name="biographie"></textarea>
    <br>
    <br>
    
    <label for="loisir_1">Loisir 1</label>
    <br>
    <input type="text" id="loisir_1" name="loisir_1" />
    <br>
    <br>

    <label for="loisir_2">Loisir 2</label>
    <br>
    <input type="text" id="loisir_2" name="loisir_2" />
    <br>
    <br>

    <label for="loisir_3">Loisir 3</label>
    <br>
    <input type="text" id="loisir_3" name="loisir_3" />
    <br>
    <br>

    <label for="loisir_4">Loisir 4</label>
    <br>
    <input type="text" id="loisir_4" name="loisir_4" />
    <br>
    <br>
</div>