<div class=alinea>
    <input type="checkbox" id="html" name="Langage_prog[]" value="html">
    <label for="html">HTML</label>
    <br>

    <input type="checkbox" id="css" name="Langage_prog[]" value="css">
    <label for="css">CSS</label>
    <br>

    <input type="checkbox" id="javascript" name="Langage_prog[]" value="javascript">
    <label for="javascript">JavaScript</label>
    <br>

    <input type="checkbox" id="php" name="Langage_prog[]" value="php">
    <label for="php">PHP</label>
    <br>

    <input type="checkbox" id="sql" name="Langage_prog[]" value="sql">
    <label for="sql">SQL</label>
    <br>
</div>
