<div class=alinea>
    <input type="checkbox" id="francais" name="langues[]" value="francais">
    <label for="francais">Français</label>
    <br>

    <input type="checkbox" id="anglais" name="langues[]" value="anglais">
    <label for="anglais">Anglais</label>
    <br>

    <input type="checkbox" id="arabe" name="langues[]" value="arabe">
    <label for="arabe">Arabe</label>
    <br>

    <input type="checkbox" id="breton" name="langues[]" value="breton">
    <label for="breton">Breton</label>
    <br>

    <input type="checkbox" id="espagnol" name="langues[]" value="espagnol">
    <label for="espagnol">Espagnol</label>
    <br>
</div>
