<div class=alinea>
    <input type="checkbox" id="photoshop" name="logiciel[]" value="Photoshop">
    <label for="photoshop">Photoshop</label>
    <br>

    <input type="checkbox" id="illustrator" name="logiciel[]" value="Illustrator">
    <label for="illustrator">Illustrator</label>
    <br>

    <input type="checkbox" id="xd" name="logiciel[]" value="XD">
    <label for="xd">XD</label>
    <br>

    <input type="checkbox" id="figma" name="logiciel[]" value="Figma">
    <label for="figma">Figma</label>
    <br>
</div>
