<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Formulaire</title>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
  
    <link rel="preconnect" href="https://fonts.googleapis.com">  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
</head>
<body>
    
    <header>
        <h1><?= $formData["firstName"]." ".$formData["lastName"]; ?></h1>
        <h2>Développeur WEB</h2>
    </header>
    
    <section>
        <div id=cv_colonne_gauche>
            <h1>INFORMATIONS</h1>
            <h2>Contact</h2>
            <h3>Email</h3>
            <p><?= $formData["email"]; ?></p>
            <h3>Téléphone</h3>
            <p><?= $formData["phone"]; ?></p>
            <h3>Linkedin</h3>
            <p><?= $formData["linkedin"]; ?></p>
            <h3>GitHub</h3>
            <p><?= $formData["github"]; ?></p>
            
            <h2>Biographie</h2>
            <p><?php echo $formData["biographie"]; ?></p>
            
            <h2>Loisirs</h2>
            <dl>
                <li><?php echo $formData["loisir_1"]; ?></li>
                <li><?php echo $formData["loisir_2"]; ?></li>
                <li><?php echo $formData["loisir_3"]; ?></li>
                <li><?php echo $formData["loisir_4"]; ?></li>
            </dl>
        </div>
        
        <div id=cv_colonne_gauche>
            <h1>COMPETENCES</h1>
            <h2>Langages de programmation</h2>
            <dl>
                    <?php foreach ($formData["langage"] as $langue): ?>
                        <li><?php echo $langue; ?></li>
                    <?php endforeach; ?>
            </dl>
            
            <h2>Frameworks & Librairies</h2>
            <dl>
                    <?php foreach ($formData["frameworks"] as $frame): ?>
                        <li><?php echo $frame; ?></li>
                    <?php endforeach; ?>
            </dl>
            
            <h2>Logiciels</h2>
            <dl>
                    <?php foreach ($formData["logiciels"] as $langue): ?>
                        <li><?php echo $langue; ?></li>
                    <?php endforeach; ?>
            </dl>
            
            <h2>Langues</h2>
            <dl>
                    <?php foreach ($formData["langues"] as $langue): ?>
                        <li><?php echo $langue; ?></li>
                    <?php endforeach; ?>
            </dl>
            
        </div>
    </section>

</body>
</html>