<!--Dans home.phtml ajoutez un formulaire qui vous permettra à l'aide d'un <select> qui permettra de choisir entre la page about et la page contact.-->


<h1>Page d'accueil</h1>

<form action="index.php" method="get">
    <fieldset>
        <label for="route">Ou souhaitez-vous aller ?</label><br>
        <select name="route">
            <option value="">- - -</option>
            <option value="contact">Contacts</option>
            <option value="about">A propos</option>
        </select>
        <input type="submit" value="Valider">
    </fieldset>
</form>

<a href="https://vincentollivier.sites.3wa.io/04-php/res03-php-j2/Mini%20Projet%20Routing/index.php?route=contact">Contacts</a><br>
<a href="https://vincentollivier.sites.3wa.io/04-php/res03-php-j2/Mini%20Projet%20Routing/index.php?route=about">A propos</a>

